---
name: Publish package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Get versions
        id: versions
        run: |
          java_version=$(grep -Eo 'java [a-z0-9.-]+' .tool-versions | cut -d'-' -f2)
          echo "java=$java_version" >> $GITHUB_OUTPUT
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ steps.versions.outputs.java }}
          distribution: temurin
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Publish package
        run: gradle publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
