---
name: Release

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "v*.*.*"

jobs:
  github:
    name: GitHub
    uses: fabasoad/reusable-workflows/.github/workflows/wf-github-release.yml@dependabot/github_actions/zaproxy/action-api-scan-0.8.0
    with:
      bump-tags: false
