---
name: Security

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['java']
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Get versions
        id: versions
        run: |
          java_version=$(grep -Eo 'java [a-z0-9.-]+' .tool-versions | cut -d'-' -f2)
          echo "java=$java_version" >> $GITHUB_OUTPUT
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ steps.versions.outputs.java }}
          distribution: temurin
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: Build with Gradle
        env:
          SKIP_FINALIZE: true
        run: ./gradlew build
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
