---
name: Security Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  codeql_tests:
    name: CodeQL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['java']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get java version
        id: java-version
        run: |
          major=$(cut -c 1-2 .java-version)
          echo "MAJOR=$major" >> $GITHUB_OUTPUT
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ steps.java-version.outputs.MAJOR }}
          distribution: adopt
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: Build with Gradle
        env:
          SKIP_FINALIZE: true
        run: ./gradlew build
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
