---
name: Unit Tests

on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - gradle/**
      - tasks/Makefile.java.mk
      - Makefile
      - src/**
      - build.gradle
      - ./gradlew
      - ./gradlew.bat
  push:
    branches:
      - main

jobs:
  gradle:
    name: Gradle
    uses: fabasoad/reusable-workflows/.github/workflows/wf-java-unit-tests.yml@feat/java-ut
