---
name: Unit Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  unit_tests:
    name: Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        env:
          SKIP_FINALIZE: true
        run: ./gradlew build
      - name: Unit tests
        run: ./gradlew test
