---
name: Unit Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  unit-tests:
    name: Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Get versions
        id: versions
        run: |
          java_version=$(grep -Eo 'java [a-z0-9.-]+' .tool-versions | cut -d'-' -f2)
          echo "java=$java_version" >> $GITHUB_OUTPUT
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ steps.versions.outputs.java }}
          distribution: temurin
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build
        env:
          SKIP_FINALIZE: true
        run: ./gradlew build
      - name: Unit tests
        run: ./gradlew test
