---
name: Unit Tests

on:
  push:
    branches:
      - 'dependabot/*'
      - 'feature-**'
      - 'fix-**'
      - 'main'
      - 'snyk-upgrade-**'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  unit_tests:
    name: Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Build with Gradle
        run: ./gradlew build
      - name: Unit tests
        run: ./gradlew test
