---
name: Unit Tests

on:
  push:
    branches:
      - 'main'
      - 'bugfix/**'
      - 'dependabot/*'
      - 'feature-**'
      - 'snyk-upgrade-**'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  unit_tests:
    name: Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Build with Gradle
        run: ./gradlew build
      - name: Unit tests with coverage
        uses: paambaati/codeclimate-action@v2.7.5
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: ./gradlew test
          debug: true
